version: "3.8"

services:
  nginx:
    image: nginx:stable
    container_name: pve-nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf